
parameters:
  - name: Major
    type: number 
    default: 0 
  - name: Minor
    type: number 
    default: 0 
  - name: Patch
    type: number 


trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '**/PetaPoco.Repository.Abstractions.csproj'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
