
parameters:
  - name: VersionNumber
    type: string 
    default: '0.0.'

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: '**/PetaPoco.Repository.Abstractions.csproj'
    versioningScheme: byPrereleaseNumber
    versionEnvVar: VersionNumber
    outputDir: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'