
parameters:
  - name: VersionNumber
    type: string 
    default: '1.0.'
    
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  packageVersion: ${{ parameters.VersionNumber }}

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: '**/PetaPoco.Repository.Abstractions.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: packageVersion
    outputDir: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'